"""NLLB/FLORES language choices: (label, code)."""

NLLB_LANGUAGE_CHOICES = [
    ("Acehnese (Arabic script) (ace_Arab)", "ace_Arab"),
    ("Acehnese (Latin script) (ace_Latn)", "ace_Latn"),
    ("Afrikaans (afr_Latn)", "afr_Latn"),
    ("Akan (aka_Latn)", "aka_Latn"),
    ("Amharic (amh_Ethi)", "amh_Ethi"),
    ("Armenian (hye_Armn)", "hye_Armn"),
    ("Assamese (asm_Beng)", "asm_Beng"),
    ("Asturian (ast_Latn)", "ast_Latn"),
    ("Awadhi (awa_Deva)", "awa_Deva"),
    ("Ayacucho Quechua (quy_Latn)", "quy_Latn"),
    ("Balinese (ban_Latn)", "ban_Latn"),
    ("Bambara (bam_Latn)", "bam_Latn"),
    ("Banjar (Arabic script) (bjn_Arab)", "bjn_Arab"),
    ("Banjar (Latin script) (bjn_Latn)", "bjn_Latn"),
    ("Bashkir (bak_Cyrl)", "bak_Cyrl"),
    ("Basque (eus_Latn)", "eus_Latn"),
    ("Belarusian (bel_Cyrl)", "bel_Cyrl"),
    ("Bemba (bem_Latn)", "bem_Latn"),
    ("Bengali (ben_Beng)", "ben_Beng"),
    ("Bhojpuri (bho_Deva)", "bho_Deva"),
    ("Bosnian (bos_Latn)", "bos_Latn"),
    ("Buginese (bug_Latn)", "bug_Latn"),
    ("Bulgarian (bul_Cyrl)", "bul_Cyrl"),
    ("Burmese (mya_Mymr)", "mya_Mymr"),
    ("Catalan (cat_Latn)", "cat_Latn"),
    ("Cebuano (ceb_Latn)", "ceb_Latn"),
    ("Central Atlas Tamazight (tzm_Tfng)", "tzm_Tfng"),
    ("Central Aymara (ayr_Latn)", "ayr_Latn"),
    ("Central Kanuri (Arabic script) (knc_Arab)", "knc_Arab"),
    ("Central Kanuri (Latin script) (knc_Latn)", "knc_Latn"),
    ("Central Kurdish (ckb_Arab)", "ckb_Arab"),
    ("Chhattisgarhi (hne_Deva)", "hne_Deva"),
    ("Chinese (Simplified) (zho_Hans)", "zho_Hans"),
    ("Chinese (Traditional) (zho_Hant)", "zho_Hant"),
    ("Chokwe (cjk_Latn)", "cjk_Latn"),
    ("Crimean Tatar (crh_Latn)", "crh_Latn"),
    ("Croatian (hrv_Latn)", "hrv_Latn"),
    ("Czech (ces_Latn)", "ces_Latn"),
    ("Danish (dan_Latn)", "dan_Latn"),
    ("Dari (prs_Arab)", "prs_Arab"),
    ("Dutch (nld_Latn)", "nld_Latn"),
    ("Dyula (dyu_Latn)", "dyu_Latn"),
    ("Dzongkha (dzo_Tibt)", "dzo_Tibt"),
    ("Eastern Panjabi (pan_Guru)", "pan_Guru"),
    ("Eastern Yiddish (ydd_Hebr)", "ydd_Hebr"),
    ("Egyptian Arabic (arz_Arab)", "arz_Arab"),
    ("English (eng_Latn)", "eng_Latn"),
    ("Esperanto (epo_Latn)", "epo_Latn"),
    ("Estonian (est_Latn)", "est_Latn"),
    ("Ewe (ewe_Latn)", "ewe_Latn"),
    ("Faroese (fao_Latn)", "fao_Latn"),
    ("Fijian (fij_Latn)", "fij_Latn"),
    ("Finnish (fin_Latn)", "fin_Latn"),
    ("Fon (fon_Latn)", "fon_Latn"),
    ("French (fra_Latn)", "fra_Latn"),
    ("Friulian (fur_Latn)", "fur_Latn"),
    ("Galician (glg_Latn)", "glg_Latn"),
    ("Ganda (lug_Latn)", "lug_Latn"),
    ("Georgian (kat_Geor)", "kat_Geor"),
    ("German (deu_Latn)", "deu_Latn"),
    ("Greek (ell_Grek)", "ell_Grek"),
    ("Guarani (grn_Latn)", "grn_Latn"),
    ("Gujarati (guj_Gujr)", "guj_Gujr"),
    ("Haitian Creole (hat_Latn)", "hat_Latn"),
    ("Halh Mongolian (khk_Cyrl)", "khk_Cyrl"),
    ("Hausa (hau_Latn)", "hau_Latn"),
    ("Hebrew (heb_Hebr)", "heb_Hebr"),
    ("Hindi (hin_Deva)", "hin_Deva"),
    ("Hungarian (hun_Latn)", "hun_Latn"),
    ("Icelandic (isl_Latn)", "isl_Latn"),
    ("Igbo (ibo_Latn)", "ibo_Latn"),
    ("Ilocano (ilo_Latn)", "ilo_Latn"),
    ("Indonesian (ind_Latn)", "ind_Latn"),
    ("Irish (gle_Latn)", "gle_Latn"),
    ("Italian (ita_Latn)", "ita_Latn"),
    ("Japanese (jpn_Jpan)", "jpn_Jpan"),
    ("Javanese (jav_Latn)", "jav_Latn"),
    ("Jingpho (kac_Latn)", "kac_Latn"),
    ("Kabiyè (kbp_Latn)", "kbp_Latn"),
    ("Kabuverdianu (kea_Latn)", "kea_Latn"),
    ("Kabyle (kab_Latn)", "kab_Latn"),
    ("Kamba (kam_Latn)", "kam_Latn"),
    ("Kannada (kan_Knda)", "kan_Knda"),
    ("Kashmiri (Arabic script) (kas_Arab)", "kas_Arab"),
    ("Kashmiri (Devanagari script) (kas_Deva)", "kas_Deva"),
    ("Kazakh (kaz_Cyrl)", "kaz_Cyrl"),
    ("Khmer (khm_Khmr)", "khm_Khmr"),
    ("Kikongo (kon_Latn)", "kon_Latn"),
    ("Kikuyu (kik_Latn)", "kik_Latn"),
    ("Kimbundu (kmb_Latn)", "kmb_Latn"),
    ("Kinyarwanda (kin_Latn)", "kin_Latn"),
    ("Korean (kor_Hang)", "kor_Hang"),
    ("Kyrgyz (kir_Cyrl)", "kir_Cyrl"),
    ("Lao (lao_Laoo)", "lao_Laoo"),
    ("Latgalian (ltg_Latn)", "ltg_Latn"),
    ("Ligurian (lij_Latn)", "lij_Latn"),
    ("Limburgish (lim_Latn)", "lim_Latn"),
    ("Lingala (lin_Latn)", "lin_Latn"),
    ("Lithuanian (lit_Latn)", "lit_Latn"),
    ("Lombard (lmo_Latn)", "lmo_Latn"),
    ("Luba-Kasai (lua_Latn)", "lua_Latn"),
    ("Luo (luo_Latn)", "luo_Latn"),
    ("Luxembourgish (ltz_Latn)", "ltz_Latn"),
    ("Macedonian (mkd_Cyrl)", "mkd_Cyrl"),
    ("Magahi (mag_Deva)", "mag_Deva"),
    ("Maithili (mai_Deva)", "mai_Deva"),
    ("Malayalam (mal_Mlym)", "mal_Mlym"),
    ("Maltese (mlt_Latn)", "mlt_Latn"),
    ("Maori (mri_Latn)", "mri_Latn"),
    ("Marathi (mar_Deva)", "mar_Deva"),
    ("Meitei (Bengali script) (mni_Beng)", "mni_Beng"),
    ("Mesopotamian Arabic (acm_Arab)", "acm_Arab"),
    ("Minangkabau (Arabic script) (min_Arab)", "min_Arab"),
    ("Minangkabau (Latin script) (min_Latn)", "min_Latn"),
    ("Mizo (lus_Latn)", "lus_Latn"),
    ("Modern Standard Arabic (arb_Arab)", "arb_Arab"),
    ("Modern Standard Arabic (Romanized) (arb_Latn)", "arb_Latn"),
    ("Moroccan Arabic (ary_Arab)", "ary_Arab"),
    ("Mossi (mos_Latn)", "mos_Latn"),
    ("Najdi Arabic (ars_Arab)", "ars_Arab"),
    ("Nepali (npi_Deva)", "npi_Deva"),
    ("Nigerian Fulfulde (fuv_Latn)", "fuv_Latn"),
    ("North Azerbaijani (azj_Latn)", "azj_Latn"),
    ("North Levantine Arabic (apc_Arab)", "apc_Arab"),
    ("Northern Kurdish (kmr_Latn)", "kmr_Latn"),
    ("Northern Sotho (nso_Latn)", "nso_Latn"),
    ("Northern Uzbek (uzn_Latn)", "uzn_Latn"),
    ("Norwegian Bokmål (nob_Latn)", "nob_Latn"),
    ("Norwegian Nynorsk (nno_Latn)", "nno_Latn"),
    ("Nuer (nus_Latn)", "nus_Latn"),
    ("Nyanja (nya_Latn)", "nya_Latn"),
    ("Occitan (oci_Latn)", "oci_Latn"),
    ("Odia (ory_Orya)", "ory_Orya"),
    ("Pangasinan (pag_Latn)", "pag_Latn"),
    ("Papiamento (pap_Latn)", "pap_Latn"),
    ("Plateau Malagasy (plt_Latn)", "plt_Latn"),
    ("Polish (pol_Latn)", "pol_Latn"),
    ("Portuguese (por_Latn)", "por_Latn"),
    ("Romanian (ron_Latn)", "ron_Latn"),
    ("Rundi (run_Latn)", "run_Latn"),
    ("Russian (rus_Cyrl)", "rus_Cyrl"),
    ("Samoan (smo_Latn)", "smo_Latn"),
    ("Sango (sag_Latn)", "sag_Latn"),
    ("Sanskrit (san_Deva)", "san_Deva"),
    ("Santali (sat_Olck)", "sat_Olck"),
    ("Sardinian (srd_Latn)", "srd_Latn"),
    ("Scottish Gaelic (gla_Latn)", "gla_Latn"),
    ("Serbian (srp_Cyrl)", "srp_Cyrl"),
    ("Shan (shn_Mymr)", "shn_Mymr"),
    ("Shona (sna_Latn)", "sna_Latn"),
    ("Sicilian (scn_Latn)", "scn_Latn"),
    ("Silesian (szl_Latn)", "szl_Latn"),
    ("Sindhi (snd_Arab)", "snd_Arab"),
    ("Sinhala (sin_Sinh)", "sin_Sinh"),
    ("Slovak (slk_Latn)", "slk_Latn"),
    ("Slovenian (slv_Latn)", "slv_Latn"),
    ("Somali (som_Latn)", "som_Latn"),
    ("South Azerbaijani (azb_Arab)", "azb_Arab"),
    ("South Levantine Arabic (ajp_Arab)", "ajp_Arab"),
    ("Southern Pashto (pbt_Arab)", "pbt_Arab"),
    ("Southern Sotho (sot_Latn)", "sot_Latn"),
    ("Southwestern Dinka (dik_Latn)", "dik_Latn"),
    ("Spanish (spa_Latn)", "spa_Latn"),
    ("Standard Latvian (lvs_Latn)", "lvs_Latn"),
    ("Standard Malay (zsm_Latn)", "zsm_Latn"),
    ("Standard Tibetan (bod_Tibt)", "bod_Tibt"),
    ("Sundanese (sun_Latn)", "sun_Latn"),
    ("Swahili (swh_Latn)", "swh_Latn"),
    ("Swati (ssw_Latn)", "ssw_Latn"),
    ("Swedish (swe_Latn)", "swe_Latn"),
    ("Tagalog (tgl_Latn)", "tgl_Latn"),
    ("Tajik (tgk_Cyrl)", "tgk_Cyrl"),
    ("Tamasheq (Latin script) (taq_Latn)", "taq_Latn"),
    ("Tamasheq (Tifinagh script) (taq_Tfng)", "taq_Tfng"),
    ("Tamil (tam_Taml)", "tam_Taml"),
    ("Tatar (tat_Cyrl)", "tat_Cyrl"),
    ("Ta’izzi-Adeni Arabic (acq_Arab)", "acq_Arab"),
    ("Telugu (tel_Telu)", "tel_Telu"),
    ("Thai (tha_Thai)", "tha_Thai"),
    ("Tigrinya (tir_Ethi)", "tir_Ethi"),
    ("Tok Pisin (tpi_Latn)", "tpi_Latn"),
    ("Tosk Albanian (als_Latn)", "als_Latn"),
    ("Tsonga (tso_Latn)", "tso_Latn"),
    ("Tswana (tsn_Latn)", "tsn_Latn"),
    ("Tumbuka (tum_Latn)", "tum_Latn"),
    ("Tunisian Arabic (aeb_Arab)", "aeb_Arab"),
    ("Turkish (tur_Latn)", "tur_Latn"),
    ("Turkmen (tuk_Latn)", "tuk_Latn"),
    ("Twi (twi_Latn)", "twi_Latn"),
    ("Ukrainian (ukr_Cyrl)", "ukr_Cyrl"),
    ("Umbundu (umb_Latn)", "umb_Latn"),
    ("Urdu (urd_Arab)", "urd_Arab"),
    ("Uyghur (uig_Arab)", "uig_Arab"),
    ("Venetian (vec_Latn)", "vec_Latn"),
    ("Vietnamese (vie_Latn)", "vie_Latn"),
    ("Waray (war_Latn)", "war_Latn"),
    ("Welsh (cym_Latn)", "cym_Latn"),
    ("West Central Oromo (gaz_Latn)", "gaz_Latn"),
    ("Western Persian (pes_Arab)", "pes_Arab"),
    ("Wolof (wol_Latn)", "wol_Latn"),
    ("Xhosa (xho_Latn)", "xho_Latn"),
    ("Yoruba (yor_Latn)", "yor_Latn"),
    ("Yue Chinese (yue_Hant)", "yue_Hant"),
    ("zho_Hant (zho_trad)", "zho_trad"),
    ("Zulu (zul_Latn)", "zul_Latn"),
]
